# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Post.create([
	{title: "Phase 3 Time.", body: "Keytar selvage artisan tote bag gentrify. Shoreditch offal succulents whatever williamsburg kickstarter twee tofu poke pour-over banjo disrupt. Readymade kogi chia YOLO blue bottle bicycle rights forage wayfarers helvetica 90's prism. Salvia tbh franzen trust fund scenester iPhone. Air plant poke live-edge bitters letterpress woke pug pork belly. Four loko coloring book kinfolk activated charcoal tote bag authentic ramps cronut. Polaroid swag fanny pack, mustache cornhole asymmetrical banh mi meggings twee tumeric gastropub cliche cray. Affogato letterpress biodiesel coloring book vexillologist synth PBR&B, fingerstache cardigan prism cred."},
	{title: "Gilmore Girls.", body: "Twee succulents pug 3 wolf moon bitters blue bottle. Drinking vinegar tattooed try-hard, gentrify distillery schlitz hashtag fixie la croix pabst. Microdosing shoreditch tofu, sartorial brooklyn vice flannel mumblecore marfa pop-up farm-to-table af. Kale chips cronut pork belly locavore, palo santo dreamcatcher sriracha mlkshk pitchfork normcore pug. Ramps literally deep v woke sustainable mlkshk, keytar PBR&B schlitz cray banh mi. Vaporware man braid brooklyn snackwave trust fund pok pok, chillwave godard cray."},
	{title: "Hipster Ipsum.", body: "Twee succulents pug 3 wolf moon bitters blue bottle. Drinking vinegar tattooed try-hard, gentrify distillery schlitz hashtag fixie la croix pabst. Microdosing shoreditch tofu, sartorial brooklyn vice flannel mumblecore marfa pop-up farm-to-table af. Kale chips cronut pork belly locavore, palo santo dreamcatcher sriracha mlkshk pitchfork normcore pug. Ramps literally deep v woke sustainable mlkshk, keytar PBR&B schlitz cray banh mi. Vaporware man braid brooklyn snackwave trust fund pok pok, chillwave godard cray."},
	{title: "Dev Bootcamp.", body: "Twee succulents pug 3 wolf moon bitters blue bottle. Drinking vinegar tattooed try-hard, gentrify distillery schlitz hashtag fixie la croix pabst. Microdosing shoreditch tofu, sartorial brooklyn vice flannel mumblecore marfa pop-up farm-to-table af. Kale chips cronut pork belly locavore, palo santo dreamcatcher sriracha mlkshk pitchfork normcore pug. Ramps literally deep v woke sustainable mlkshk, keytar PBR&B schlitz cray banh mi. Vaporware man braid brooklyn snackwave trust fund pok pok, chillwave godard cray."},
	{title: "Tv Shows.", body: "Twee succulents pug 3 wolf moon bitters blue bottle. Drinking vinegar tattooed try-hard, gentrify distillery schlitz hashtag fixie la croix pabst. Microdosing shoreditch tofu, sartorial brooklyn vice flannel mumblecore marfa pop-up farm-to-table af. Kale chips cronut pork belly locavore, palo santo dreamcatcher sriracha mlkshk pitchfork normcore pug. Ramps literally deep v woke sustainable mlkshk, keytar PBR&B schlitz cray banh mi. Vaporware man braid brooklyn snackwave trust fund pok pok, chillwave godard cray."},
	{title: "Graduation.", body: "Twee succulents pug 3 wolf moon bitters blue bottle. Drinking vinegar tattooed try-hard, gentrify distillery schlitz hashtag fixie la croix pabst. Microdosing shoreditch tofu, sartorial brooklyn vice flannel mumblecore marfa pop-up farm-to-table af. Kale chips cronut pork belly locavore, palo santo dreamcatcher sriracha mlkshk pitchfork normcore pug. Ramps literally deep v woke sustainable mlkshk, keytar PBR&B schlitz cray banh mi. Vaporware man braid brooklyn snackwave trust fund pok pok, chillwave godard cray."},
	{title: "Final Projects.", body: "Twee succulents pug 3 wolf moon bitters blue bottle. Drinking vinegar tattooed try-hard, gentrify distillery schlitz hashtag fixie la croix pabst. Microdosing shoreditch tofu, sartorial brooklyn vice flannel mumblecore marfa pop-up farm-to-table af. Kale chips cronut pork belly locavore, palo santo dreamcatcher sriracha mlkshk pitchfork normcore pug. Ramps literally deep v woke sustainable mlkshk, keytar PBR&B schlitz cray banh mi. Vaporware man braid brooklyn snackwave trust fund pok pok, chillwave godard cray."}
	



	])	
